install:
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  - node -e "console.log(process.env)"
  - cd /d "%VS100COMNTOOLS%" && dir && tree
  - cd /d "%VS110COMNTOOLS%" && dir && tree
  - cd /d "%VS120COMNTOOLS%" && dir && tree
  - cd /d "%VS140COMNTOOLS%" && dir && tree
  - cd /d "%VS90COMNTOOLS%" && dir && tree

build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm build

# Don't actually build.
build: off
