install:
  # install modules
  - npm install
  - ps: Start-FileDownload 'https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe'
  - dir
  - 7z x htmlhelp.exe -o"%TEMP%\HTML Help Workshop"
  - del htmlhelp.exe
 
# Post-install test scripts.
test_script:
  - node -e "console.log(process.env)"

build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm build

# Don't actually build.
build: off
