install:
  # install modules
  - curl -L -o "%TEMP%\htmlhelp.exe" https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
  - npm install
  - 7z x "%TEMP%\htmlhelp.exe" -o"%TEMP%\HTML Help Workshop"

build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run build

artifacts:
  - path: css.chm
    name: CSS 手册
