install:
  # install modules
  - curl -L -o "%TEMP%\htmlhelp.exe" https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
  - npm install
  - 7z x "%TEMP%\htmlhelp.exe" -o"%TEMP%\HTML Help Workshop"

build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run build

deploy:
  release: ci-v$(appveyor_build_version)
  description: "由appveyor 自动发布"
  provider: GitHub
  auth_token:
    # your encrypted token from GitHub
    secure: YEJZUH9eUbhJGdvS13k/n05NwM/OAEGuLA0WjpOyypUEUk/PppQlYjrH8uKA0vuU
  # upload chm file to release assets
  artifact: css.chm
  draft: false
  prerelease: false
  on:
    # release from gh-pages branch only
    branch: gh-pages
    appveyor_repo_tag: true
