install:
  # 安装npm包
  - npm install

test_script:
  - npm run test

before_build:
  # 下载HTML Help Workshop
  - curl -L -o "%TEMP%\htmlhelp.exe" https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe
  # 解压htmlhelp.exe到%TEMP%\HTML Help Workshop
  - 7z x "%TEMP%\htmlhelp.exe" -o"%TEMP%\HTML Help Workshop"

build_script:
  # 编译chm文件
  - npm run build

after_build:
  # 压缩chm文件为zip包
  - echo 详见：http://jingyan.baidu.com/article/6079ad0e491bd228ff86db8a.html>chm打开是空白的解决办法.txt
  - 7z a css.zip css.chm chm打开是空白的解决办法.txt

artifacts:
  - path: css.chm
    name: CSS 手册

  - path: css.zip
    name: CSS 手册 压缩包
