install:
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  - node -e "console.log(process.env)"
  - for /r c:\ %i in (*) do @echo %i

build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm build

# Don't actually build.
build: off
